### ISSUE TITLE
Getting errors and unable to import from Catmaid.

### ISSUE THREAD

**Issue by calleschulers** [schlegelp/CATMAID-to-Blender#10]
Hi Phillip - 

When attempting to pull in neurons by annonation or skeleton ID I receive the following errors. 

![annotation](https://cloud.githubusercontent.com/assets/22100705/19206905/3c0f4946-8cba-11e6-9dce-6048c8fc9e3c.png)

![skeleton id](https://cloud.githubusercontent.com/assets/22100705/19206913/4e2a5dc8-8cba-11e6-87ce-4bd515e01dab.png)

I am installing Blender on a new computer so I downloaded the Catmaid-to-Blender import addon and was able to connect without a problem. However, I am still unable to retrieve any neurons. If you could help me to understand what may be going wrong, I would greatly appreciate it.

Thank you

**Comment by schlegelp** [comment]
Hi! Sorry for the late response. What version of CATMAID are you running?
