### ISSUE TITLE
Color neurons by annotations feature not working properly

### ISSUE THREAD

**Issue by bakoppenhaver** [schlegelp/CATMAID-to-Blender#4]
I am attempting to colorize neurons imported from CATMAID by their respective annotations but it is colorizing everything in the 3D space to the single color selected within this feature. Let me just walk through my process to better help you understand what I mean.

I first import by annotation i.e "KCaBp" 
This loads in about 10 neuron skeletons.
Then I use the color by annotations feature to color any "KCaBp" brown and leave the exclude box blank.
This works fine, every KCaBp changes to brown.

I again import by annotation but this time "KCy"
This loads in around 65 neuron skeletons.
Then I attempt to use the color by annotations feature again but color the "KCy" cyan.
(I attempted to use and disregard the exclude box as an experiment since the color by annotations feature was causing me trouble.)
When I did use the exclude box I typed in "KCaBp" so that it would not change the color of the KCaBp neurons to cyan, leaving them brown.

However, this would change everything in the 3D space to cyan (both KCy and KCaBp).

**Comment by schlegelp** [comment]
Hey, sorry for not reacting earlier. I will look into it ASAP!

**Comment by schlegelp** [comment]
I tried reproducing this error with my own neurons but it seems to work fine. Am I correct to assume that none of your ~75 neurons has both annotations? In that case you should not need the exclude box anyway.

What happens if you change the material color of one of the neurons manually? Do the others change as well?

I added some additional feedback to the current version of the addon. Could you install it and run it in your scenario again? If it still causes problems, please send me a screenshot of the console (like the one attached)

![annotations](https://cloud.githubusercontent.com/assets/7161148/13987476/072d0df6-f108-11e5-856f-73c085ad3e78.PNG)

**Comment by bakoppenhaver** [comment]
Thanks for looking into it! Also I really like the new way to connect to CATMAID you implemented. Making it save your credentials was a great idea for convenience! 

So I just tried to repeat my same experiment as before. Coloring the KCaBp cells brown first then I followed it up by making the KCy cells cyan. this time it changed the KCy cyan but reset the KCaBp to the default grey material. But yes none of the neurons have both annotations.

Here are some screenshots:
<img width="429" alt="annotation color" src="https://cloud.githubusercontent.com/assets/17882983/13996287/5f0ae5b6-f103-11e5-8084-7d7540de78f1.png">
<img width="1394" alt="first color-kcabp" src="https://cloud.githubusercontent.com/assets/17882983/13996288/5f0c2c82-f103-11e5-8ac8-36e437226c92.png">
<img width="1395" alt="second color-kcy" src="https://cloud.githubusercontent.com/assets/17882983/13996286/5f0ab3ac-f103-11e5-9344-84b9e98bdad4.png">

**Comment by schlegelp** [comment]
Ok, looks like it is working as intended. You probably have "Color others grey" checked - this is why neurons that do not have the "KCy" annotation are made grey. Just uncheck that box and it should work. Let me know how it went!

**Comment by bakoppenhaver** [comment]
Ah, yes! I don't recall that box being present when I first opened up this issue. That must have been the issue after the new update. Thank you so much for helping me with this!

**Comment by schlegelp** [comment]
No prob. Always glad when someone is using the plugin. Let me know if you run into any other issues or have a feature request.

**Comment by bakoppenhaver** [comment]
Hey Phillipp,

I actually do have a feature request that would help our lab a ton! Would it be possible to create a selection tab where we can select neurons by their annotations? I have a group of KCaBc and a group KCaBs that have a mutual annotation Bundle 1 Seed. It would be nice to be able to select them by that annotation rather than import copies of the same cells by importing via the Bundle 1 Seed annotation.

Thanks,
Ben Koppenhaver

**Comment by bakoppenhaver** [comment]
Also is there a reason why the color by annotation feature creates 1 material for each cell individually but gives them all the same color value? Would it be possible for it to create just 1 material that is assigned to anything with the desired annotation?

**Comment by schlegelp** [comment]
Hi Ben,

I added a select by annotation feature - just download the recent version. As per usual, you can enter multiple annotations separated by a comma but without space (e.g. "KCaBC,KCAbs"). Maybe I will implement this as a dropdown menu in a later version. But it should already do the trick as it is now.

![select by annotation](https://cloud.githubusercontent.com/assets/7161148/14046847/5dfe89c8-f2a4-11e5-94e8-21776e498f35.PNG)

The reason for every single neuron having it's own material is to keep things flexible. If you were to give all neurons a single material but later on you want to change only a subset of them, you would have to go back and assign a different material for those subsets. This would definitely be possible but also make things more difficult under certain situations. 
However, if this is interesting for you, I could add the option to use a single material. But again, this might cause trouble with other functions of the plugin that depend on neurons having individual materials.

Let me know if you need anything else.

Best,
Philipp

**Comment by bakoppenhaver** [comment]
Awesome, thanks for being so punctual and updating it so quickly! This is a very useful feature. 
I figured the materials reasoning had to do with stuff like that. That's fine there are work arounds within blender we can do. The single material feature would be nice but we don't absolutely need it, especially since like you said, it may complicate things down the road.

Sorry to bug you again though but I discovered the new selection feature needs a little bit more fine tuning. I tried to select a bundle of cells using an annotation (eg. Bundle 1 Seed) and when I moved them for animation purposes I noticed that all the inputs and outputs associated with cells having the "Bundle 1 Seed" annotation did not move because the selection tool didn't select them. 
I thought about it and it would make some sense in terms of programming, in that to my knowledge the cell skeletons themselves are the piece that actually have the annotations bound to them not the inputs and outputs. 

Let me know what you think I would be interested to learn how the selecting by annotations feature works. 

Cheers,
Ben

**Comment by schlegelp** [comment]
Whoops. Sorry, completely forgot about the connectors. Will take care of the issue this weekend. Will also give an explanation of how the selection works.

**Comment by schlegelp** [comment]
Ok, fixed it in the most recent version (also updated the latest release). Select by annotation should now select all the different objects of a neuron. But you can also exclude certain portions (e.g. just select synapses).

Here is the explanation: it is possible to attached arbitrary values to objects and save them within the .blend file. In the current version some variables are already attached to a neuron's skeleton (see screenshot). However, this is not consistent across all types of objects **yet** (e.g. somas, synapses). But as you can tell the skeleton ID is always found somewhere in the **name** of an object (e.g. 'Inputs of **123456** - neuron_name'). So what the selection function does is to first generate a list of all the skeleton IDs within your scene by iterating over all objects that start with '#**skeleton_id** - neuron_name' (which are the main skeletons). Then it retrieves a list of all the annotations attached to those skeletons from the CATMAID server. And last but not least, it iterates all objects, tries to find the skeleton ID in their name and checks in the annotation list if that skeleton_id has your requested annotation(s) attached to it. If so, they will be selected.

Hope that helps. Feel free to check in the code - that function is pretty straight forward: search for the **SelectAnnotation** class and have a look at its **execute** function.

Best,
Philipp


![object_props](https://cloud.githubusercontent.com/assets/7161148/14060108/4e75ba98-f359-11e5-8e3d-3c350253ec93.PNG)

**Comment by bakoppenhaver** [comment]
Thank you so much for all your help! This has been a great tool for our animation we are currently working on. So with your explanation in mind I was wondering if it would be possible then to have the option to make a selection have a single material across objects, which would allow for ease of manipulating textures and such. I know you wanted to avoid having it all be one material. So I am thinking by default it could do what it already does and assign a copy of the material color iterating thru the entire selection. But then have a check box or something that allows you to assign a single material to the entire selection. 

Cheers,
Ben

**Comment by schlegelp** [comment]
I added an option to "unify" the materials of given neurons after they have already been imported. Making this an option during import would have been a bit more of a hussle (but still possible). The current idea is now to import neurons, select your subgroup (e.g. by annotation) and then click "Unify Materials". There is no such this as "Individualize Materials" yet in case you want to reverse this. Let me know if this is desired.

Cheers,
Philipp

![unify_materials](https://cloud.githubusercontent.com/assets/7161148/14207580/4cf23a0e-f81b-11e5-930b-06f53a049b5a.PNG)
