### ISSUE TITLE
Python requirements

### ISSUE THREAD

**Issue by tomka** [schlegelp/CATMAID-to-Blender#6]
Using the plugin requires numpy to be installed. It would be nice to mention this in the installation notes.

**Comment by schlegelp** [comment]
The Windows version of Blender already includes numpy - is that different for other OS?

**Comment by tomka** [comment]
Oh, I see. At least on ArchLinux numpy has to be installed separately and I am pretty sure this is true for most Linux distributions.

**Comment by schlegelp** [comment]
I've updated readme.md. Feel free to add a detailed description of how to install numpy if you feel this is necessary. I also changed the script so that it does not crash if numpy is not installed - however some functions will not work but throw errors.

**Comment by schlegelp** [comment]
I'll close this issue for now. Reopen if you think this needs additional attention.

**Comment by tomka** [comment]
Thanks, I think the readme note is just fine.
