### ISSUE TITLE
Invalid SVGs

### ISSUE THREAD

**Issue by alexanderbates** [schlegelp/CATMAID-to-Blender#8]
Hey Philipp - I'm new to Blender and am trying to have a play with your excellent tools here. When I try to create an SVG for a single selected neuron using 'export connectors' tool with the same settings you have in your example on GitHub to get a neuron with a bar chart and coloured postsynapses, I do not get a 'valid' SVG. When I try to open it in Chrome, I get this complaint: 

"This page contains the following errors:

error on line 5037 at column 6: Opening and ending tag mismatch: svg line 0 and g

Below is a rendering of the page up to the first error." 

And then a small image of the neuron and its bar charts, which looks incomplete. However, the output in the terminal seems fine. I can successfully export an SVG using the export morphology option.

Any idea where I am going wrong?

Thank you!

**Comment by schlegelp** [comment]
Hi Alex,

this looks like there is a group in the svg that is not properly closed. Can you send me the SVG and a screenshot of the settings you're using for the export?

Cheers,
Philipp

**Comment by alexanderbates** [comment]
Thank you Philipp. Attached is the screenshot, here is the SVG (https://drive.google.com/open?id=0B29LAHLY0dnpcno4WEFFQTU5ZE0) and here is the terminal output generated while trying to make that file (I've tried doing all neurons with the annotation 'ASB LH Interneuron' and just selected one of those neurons, I've tried different views and with and without the CNS outline:
![screen shot 2016-06-15 at 13 24 04](https://cloud.githubusercontent.com/assets/12895900/16090252/afbb8fa2-32fc-11e6-8d0d-b4aa9915ebc3.png)

`Retrieving connector data for 1 neurons
Creating threads to retrieve skeleton data:
 Threads: 1
 Now joining threads.
 Closing Threads: 1 - 2 sExtracting coordinates..
0 Down- / 61 Upstream connectors for skid 11137808 found
Connectors successfully retrieved
Total of 61 connectors for 61 inputs found: 
Retrieving Ancestry of all upstream neurons...
Done
61 target treenodes left (0 removed by Filter)
Soma of #11137808 - down_PVL09_right_to continue found
1 Neurons in Connector data found
Writing SVG to file /Users/abates/Downloads/untitled5.svg
Creating input/weight color map...
Half_max = 5.0
28  random colors created
2  shapes created
2  random colors created
1 random colors created
Retrieving Ancestry of all upstream neurons...
Ancestry Check Done
Max connections for color_by_connection: 0
Creating neuron 11137808 ({}, {20027584: {20027570: {'presynaptic_to': 17557290, 'coords': (2.98604, 5.72, -2.83822)}}, 20716419: {15872686: {'presynaptic_to': 8689148, 'coords': (3.0374, 5.135, -2.63752)}}, 19541124: {19541114: {'presynaptic_to': 13988443, 'coords': (3.48821, 5.015, -2.5163599999999997)}}, 20716170: {22117564: {'presynaptic_to': 10495502, 'coords': (2.84455, 5.4, -2.45398)}}, 20716703: {20716704: {'presynaptic_to': 5118060, 'coords': (3.28421, 4.745, -2.65784)}}, 20829294: {20829292: {'presynaptic_to': 8069432, 'coords': (2.66323, 5.94, -2.90757)}}, 18125071: {18125069: {'presynaptic_to': 17557290, 'coords': (2.6065, 5.485, -2.9592)}}, 11137811: {11137806: {'presynaptic_to': 9539868, 'coords': (2.3628400000000003, 6.295, -3.22677)}}, 20716053: {12339705: {'presynaptic_to': 13768622, 'coords': (2.99332, 5.18, -2.62032)}}, 8940184: {8940171: {'presynaptic_to': 9539868, 'coords': (2.4460599999999997, 6.19, -3.17984)}}, 21231642: {22144872: {'presynaptic_to': 4119387, 'coords': (2.5045, 5.575, -2.70401)}}, 16242714: {16242713: {'presynaptic_to': 15588379, 'coords': (3.03867, 5.73, -2.82682)}}, 21231646: {21897590: {'presynaptic_to': 4700078, 'coords': (2.47791, 5.605, -2.7316599999999998)}}, 16301087: {16301054: {'presynaptic_to': 8069432, 'coords': (2.76241, 5.89, -2.84012)}}, 20829217: {20829218: {'presynaptic_to': 9577562, 'coords': (2.61535, 5.41, -2.95222)}}, 22157731: {22067419: {'presynaptic_to': 17819985, 'coords': (3.4690199999999995, 4.785, -2.50857)}}, 15992101: {15992098: {'presynaptic_to': 4119387, 'coords': (2.5708900000000003, 5.53, -2.56766)}}, 20829223: {20829225: {'presynaptic_to': 16289332, 'coords': (2.59692, 5.395, -2.9849)}}, 22066219: {22079740: {'presynaptic_to': 7503199, 'coords': (2.48862, 5.49, -2.64993)}}, 20829376: {20829389: {'presynaptic_to': 8177199, 'coords': (2.83423, 5.47, -2.34555)}}, 9117682: {9117620: {'presynaptic_to': 17557290, 'coords': (2.94519, 5.755, -2.87261)}}, 20829277: {12623292: {'presynaptic_to': 17557290, 'coords': (2.70598, 5.96, -2.9809099999999997)}}, 20562109: {20562135: {'presynaptic_to': 9577562, 'coords': (2.84229, 5.765, -2.94813)}}, 20829291: {20829292: {'presynaptic_to': 8069432, 'coords': (2.66684, 5.955, -2.8956)}}, 15874868: {15874864: {'presynaptic_to': 8689148, 'coords': (2.75595, 4.905, -2.5878)}}, 15740726: {15740723: {'presynaptic_to': 13986583, 'coords': (2.82977, 5.48, -2.44178)}}, 20716730: {20716748: {'presynaptic_to': 7472315, 'coords': (3.18465, 4.865, -2.7884700000000002)}}, 8608186: {8608173: {'presynaptic_to': 8698941, 'coords': (2.8918, 5.325, -2.46335)}}, 12623291: {12623292: {'presynaptic_to': 17557290, 'coords': (2.6705400000000004, 5.935, -3.04408)}}, 14558666: {14558654: {'presynaptic_to': 4119387, 'coords': (3.4545800000000004, 5.22, -2.5634799999999998)}}, 10816063: {10816037: {'presynaptic_to': 8349553, 'coords': (3.00314, 4.535, -2.42402)}}, 8993088: {8993073: {'presynaptic_to': 8980589, 'coords': (2.59958, 6.055, -2.85209)}}, 8940611: {8940599: {'presynaptic_to': 9539868, 'coords': (2.3582799999999997, 6.21, -3.06128)}}, 5584965: {5584953: {'presynaptic_to': 7503199, 'coords': (2.4331400000000003, 5.555, -2.7113)}}, 15917385: {15917383: {'presynaptic_to': 9577562, 'coords': (3.08427, 5.725, -2.7187099999999997)}}, 21513034: {21513031: {'presynaptic_to': 4119387, 'coords': (2.5403, 5.99, -2.8519)}}, 22085069: {22085066: {'presynaptic_to': 4119387, 'coords': (2.60319, 5.53, -2.61516)}}, 18290245: {18290243: {'presynaptic_to': 17425996, 'coords': (3.16255, 5.06, -3.0472200000000003)}}, 20075087: {14101782: {'presynaptic_to': 13858797, 'coords': (3.4243699999999997, 5.385, -2.5218700000000003)}}, 21231570: {22085066: {'presynaptic_to': 4119387, 'coords': (2.60529, 5.52, -2.63255)}}, 20829397: {21517173: {'presynaptic_to': 8565131, 'coords': (2.70902, 4.86, -2.622)}}, 15943382: {13385152: {'presynaptic_to': 13988443, 'coords': (3.4851699999999997, 4.985, -2.51503)}}, 20829655: {13357472: {'presynaptic_to': 16289332, 'coords': (2.56728, 5.215, -2.61725)}}, 17833167: {17833160: {'presynaptic_to': 16187214, 'coords': (2.57602, 5.37, -2.83858)}}, 5584989: {5584953: {'presynaptic_to': 7503199, 'coords': (2.46772, 5.565, -2.72498)}}, 20562143: {20562135: {'presynaptic_to': 9577562, 'coords': (2.86452, 5.765, -2.9317900000000003)}}, 20716642: {8609208: {'presynaptic_to': 8559525, 'coords': (3.01023, 4.59, -2.5683700000000003)}}, 20829243: {20829244: {'presynaptic_to': 16289332, 'coords': (2.8359400000000003, 5.88, -3.00029)}}, 15917287: {15917285: {'presynaptic_to': 9577562, 'coords': (2.92847, 5.82, -2.9104200000000002)}}, 12623335: {12623336: {'presynaptic_to': 17557290, 'coords': (2.6566799999999997, 5.965, -3.0554799999999998)}}, 15872620: {15872617: {'presynaptic_to': 8689148, 'coords': (2.76526, 4.93, -2.5752599999999997)}}, 15037294: {15037288: {'presynaptic_to': 8069432, 'coords': (2.50914, 5.57, -2.70674)}}, 7482095: {7482075: {'presynaptic_to': 15588379, 'coords': (2.52928, 4.99, -2.7665900000000003)}}, 5605361: {5605334: {'presynaptic_to': 4119387, 'coords': (2.4928, 5.485, -2.6493599999999997)}}, 15740402: {15740383: {'presynaptic_to': 13986583, 'coords': (2.7158900000000004, 5.15, -2.51015)}}, 5585011: {5584953: {'presynaptic_to': 7503199, 'coords': (2.47418, 5.585, -2.7322)}}, 18124534: {18124531: {'presynaptic_to': 8565131, 'coords': (3.4976, 4.91, -2.4904599999999997)}}, 20716665: {12505160: {'presynaptic_to': 3815491, 'coords': (2.855, 4.69, -2.45808)}}, 8070906: {8070843: {'presynaptic_to': 9539868, 'coords': (3.47263, 5.53, -2.4331400000000003)}}, 17504891: {17504889: {'presynaptic_to': 17557290, 'coords': (2.66323, 5.57, -2.98965)}}, 12623358: {18131326: {'presynaptic_to': 17557290, 'coords': (2.64946, 5.98, -3.06498)}}}, {}, {20829376: [8177199], 20716419: [8689148], 19541124: [13988443], 15037294: [8069432], 12623335: [17557290], 20716170: [10495502], 20716703: [5118060], 18125071: [17557290], 11137811: [9539868], 20716053: [13768622], 8940184: [9539868], 21231642: [4119387], 7482095: [15588379], 16242714: [15588379], 21231646: [4700078], 16301087: [8069432], 20829217: [9577562], 22157731: [17819985], 15992101: [4119387], 20829223: [16289332], 22066219: [7503199], 15740402: [13986583], 5584989: [7503199, 7503199, 7503199], 15874868: [8689148], 15740726: [13986583], 20716730: [7472315], 8608186: [8698941], 12623291: [17557290, 17557290], 14558666: [4119387], 10816063: [8349553], 20027584: [17557290], 8940611: [9539868], 5584965: [7503199, 7503199, 7503199], 15917385: [9577562], 21513034: [4119387], 22085069: [4119387, 4119387], 18290245: [17425996], 20075087: [13858797], 8993088: [8980589], 21231570: [4119387, 4119387], 20829397: [8565131], 15943382: [13988443], 20829655: [16289332], 17833167: [16187214], 20829277: [17557290, 17557290], 20562143: [9577562, 9577562], 20716642: [8559525], 20829243: [16289332], 15917287: [9577562], 20829291: [8069432, 8069432], 15872620: [8689148], 20829294: [8069432, 8069432], 20562109: [9577562, 9577562], 5605361: [4119387], 9117682: [17557290], 5585011: [7503199, 7503199, 7503199], 18124534: [8565131], 20716665: [3815491], 8070906: [9539868], 17504891: [17557290], 12623358: [17557290]})
Creating legend
Export finished`

**Comment by schlegelp** [comment]
Ok, I found the bug. As suspected the culprit was an error with the grouping. Interestingly only Chrome acts up on that - IE and CorelDraw rendered it correctly. That's why I didn't catch the bug before.
I've uploaded a [new version](https://raw.githubusercontent.com/schlegelp/CATMAID-to-Blender/master/CATMAIDImport.py) that includes some other major changes like introduction of on-screen messages. I haven't compiled it into a release yet - so click above link or download from the repository. Please let me know if you find more bugs or have a feature request!

**Comment by alexanderbates** [comment]
Hey Philipp, sorry, I have no other e-mail for you

I tried installing your updated CATMAIDImport file, but it does not seem want to work. When I try to install from file, or manually place the file in the correct folder, and then try to check the box in user preferences, I get the following error:



I also now get the same error when I try to use the .py file on your main github page.

Best,

- Alex

**Comment by schlegelp** [comment]
No problem. I found and fixed the issue. Basically what happened is that the new on-screen message system tries to initialize and find a 3D-view that it can write on. But when the plugin is initiated at the startup of Blender, there is no 3D-view port yet. Again, should be fixed now. Try downloading above file again.
