### ISSUE TITLE
Importing nodes with edited radii

### ISSUE THREAD

**Issue by BenGorko** [schlegelp/CATMAID-to-Blender#9]
Hi,
I noticed that if you change the radii of the nodes of a skeleton in Catmaid, the add-on does not import the skeletons using those radii. Would it be possible to add a feature that could do that? Also, I was wondering if it is possible to import skeletons with strahler analysis shading so main branches are brighter and more distal branches are darker or more transparent
Thanks,
Ben Gorko

**Comment by schlegelp** [comment]
Hi Ben,
currently actual node size is pretty much ignored. It is only used to identify the soma which is assumed to be the only node with radius >400. However, once in Blender, the soma always gets a standard radius.
It would relatively easy to implement that though. 
Please clarify: would you like for the radii of each node to be considered or just the actual radius of the soma?

For you second request: this is definitely possible, albeit a bit more complicated. I promise to look into that.

Best,
Philipp

**Comment by BenGorko** [comment]
Hi Philipp,
I would like the radius of every node to be considered. I edited the radius of every node I made when tracing an entire cell to create more of a volumetric representation of it.
Best,
Ben

**Comment by schlegelp** [comment]
Hi Benn,
I've pushed a new version that has both you features. Please right click [here](https://raw.githubusercontent.com/schlegelp/CATMAID-to-Blender/master/CATMAIDImport.py) to download, then replace the old file and restart Blender.
1. To import neurons with node radius simply check the "use node radii" box in the pop up
2. To color neurons by strahler, import them first. Then hit the new "By Strahler Index" button. Should be self explanatory.

Please let me know if something bugs out!

**Comment by BenGorko** [comment]
Awesome! It works great! Thank you so much!

**Comment by BenGorko** [comment]
Hi Philipp,
I actually noticed a slight issue with the skeletons imported with node radii. Specifically with the somas. It appears to still make a sphere for the soma instead of using the true radius, which creates a discontinuity between the sphere and the adjacent parts of the cell. As shown in the picture below.
Best,
Ben
![0001](https://cloud.githubusercontent.com/assets/20781425/17345737/85fedb48-58d5-11e6-8def-dfa047ea0cd2.png)

**Comment by schlegelp** [comment]
Hi Ben,
should be fixed now. Just download from the above link again or take the most recent release. Pretty cool work with that neuron! Let me know if you have any other feature request or if you run into more issues. I will close this issue in the next couple days unless something else comes up.

Cheers,
Philipp

**Comment by BenGorko** [comment]
Hi Philipp,
Nice. It looks great. That's all I have for now. Thanks for being so responsive and helpful!
Best,
Ben
